module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    setupFiles: ['<rootDir>/test/jest/set-env-vars.ts'],
    setupFilesAfterEnv: ['<rootDir>/test/jest/setup.ts'],
    cacheDirectory: '<rootDir>/dist/.cache/jest',
    testMatch: ['**/test/**/*.steps.[jt]s?(x)'],
    coverageDirectory: './jest/opt/coverage',
    collectCoverage: true,
    coveragePathIgnorePatterns: ['/node_modules/', '/test/'],
    moduleNameMapper: {
        '@controllers/(.*)': '<rootDir>/src/controllers/$1',
        '@controllers': '<rootDir>/src/controllers/index',
        '@middlewares/(.*)': '<rootDir>/src/middlewares/$1',
        '@middlewares': '<rootDir>/src/middlewares/index',
        '@models/(.*)': '<rootDir>/src/models/$1',
        '@models': '<rootDir>/src/models/index',
        '@helpers/(.*)': '<rootDir>/src/helpers/$1',
        '@helpers': '<rootDir>/src/helpers/index',
        '@schema/(.*)': '<rootDir>/src/schema/$1',
        '@schema': '<rootDir>/src/schema/index',
        '@services/(.*)': '<rootDir>/src/services/$1',
        '@services': '<rootDir>/src/services/index',
        '@shared/(.*)': '<rootDir>/src/shared/$1',
        '@shared': '<rootDir>/src/shared/index',
        '@database/(.*)': '<rootDir>/src/database/$1',
        '@database': '<rootDir>/src/database/index',
    },
    globals: {
        'ts-jest': {
            tsconfig: './tsconfig.json',
        },
    },
}
